# Generated by Django 5.1.1 on 2024-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT', '0002_remove_timetable_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_data',
            field=models.TextField(),
        ),
    ]
