# Generated by Django 5.1.1 on 2024-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT', '0003_alter_timetable_timetable_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_data',
            field=models.JSONField(),
        ),
    ]
