# Generated by Django 5.1.1 on 2024-10-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DT', '0004_alter_timetable_timetable_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
    ]
